import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

function Layout(props) {
  return (
    <div className="background-img">
      <Head>
        <title>O. Riastanjung - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      {props.children}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made using{" "}
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />|
          Copyright 2022 O.Riastanjung
        </a>
      </footer>
    </div>
  );
}

export default Layout;
