import React from 'react'
import HeadNextJS from "next/head";

function Head() {
  return (
    <HeadNextJS>
        <title>O. Riastanjung - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </HeadNextJS>
  )
}

export default Head